package Property;

public enum State {
    START,
    IDENTIFIER,
    INT,
    INT_DOT,
    DOUBLE,
    UNARY_OPERATOR,
    BINARY_OPERATOR,
    ANNOTATION_START,
    ANNOTATION_ONE_TEMP,
    ANNOTATION_ONE,
    ANNOTATION_TWO_TEMP_ONE,
    ANNOTATION_TWO_TEMP_TWO,
    ANNOTATION_TWO_TEMP_THREE,
    ANNOTATION_TWO,
    DONE,
    SINGLE_QUOTE,
    DOUBLE_QUOTE
}
